#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-sentencepiece
Version  : 0.1.99
Release  : 9
URL      : https://files.pythonhosted.org/packages/d8/87/b37ebc960d0a85e10785a1a92d796edbd975840bee150a9ae3ba5d7a0250/sentencepiece-0.1.99.tar.gz
Source0  : https://files.pythonhosted.org/packages/d8/87/b37ebc960d0a85e10785a1a92d796edbd975840bee150a9ae3ba5d7a0250/sentencepiece-0.1.99.tar.gz
Summary  : SentencePiece python wrapper
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: pypi-sentencepiece-license = %{version}-%{release}
Requires: pypi-sentencepiece-python = %{version}-%{release}
Requires: pypi-sentencepiece-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : pkgconfig(sentencepiece)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# SentencePiece Python Wrapper
Python wrapper for SentencePiece. This API will offer the encoding, decoding and training of Sentencepiece.

%package license
Summary: license components for the pypi-sentencepiece package.
Group: Default

%description license
license components for the pypi-sentencepiece package.


%package python
Summary: python components for the pypi-sentencepiece package.
Group: Default
Requires: pypi-sentencepiece-python3 = %{version}-%{release}

%description python
python components for the pypi-sentencepiece package.


%package python3
Summary: python3 components for the pypi-sentencepiece package.
Group: Default
Requires: python3-core
Provides: pypi(sentencepiece)

%description python3
python3 components for the pypi-sentencepiece package.


%prep
%setup -q -n sentencepiece-0.1.99
cd %{_builddir}/sentencepiece-0.1.99
pushd ..
cp -a sentencepiece-0.1.99 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685548175
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sentencepiece
cp %{_builddir}/sentencepiece-%{version}/sentencepiece/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sentencepiece/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/sentencepiece-%{version}/sentencepiece/third_party/absl/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sentencepiece/d5cf6efc97d21fa5e1ffd14abe61d6382c9e4701 || :
cp %{_builddir}/sentencepiece-%{version}/sentencepiece/third_party/darts_clone/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sentencepiece/1995e90082fbabd8ed1ed097878c6518ba7d826e || :
cp %{_builddir}/sentencepiece-%{version}/sentencepiece/third_party/esaxx/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sentencepiece/53af945b18e0917715623bf2ebdd6daef4c59bc2 || :
cp %{_builddir}/sentencepiece-%{version}/sentencepiece/third_party/protobuf-lite/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sentencepiece/1b5a14d06dd784e88dadc5c68344be2dc13875b6 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sentencepiece/1995e90082fbabd8ed1ed097878c6518ba7d826e
/usr/share/package-licenses/pypi-sentencepiece/1b5a14d06dd784e88dadc5c68344be2dc13875b6
/usr/share/package-licenses/pypi-sentencepiece/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-sentencepiece/53af945b18e0917715623bf2ebdd6daef4c59bc2
/usr/share/package-licenses/pypi-sentencepiece/d5cf6efc97d21fa5e1ffd14abe61d6382c9e4701

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
